# Generated by Django 6.1.2 on 2026-10-07 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_add_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('needs_data', 'Needs Data'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('inputs_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.session')),
            ],
            options={
                'abstract': False,
            },
            bases=('common.session',),
        ),
        migrations.CreateModel(
            name='ComparisonNarrative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inputs_hash', models.CharField(max_length=64)),
                ('narrative_summary', models.TextField(blank=True, default='')),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='comparisons.comparison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comparison',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='comparisons.comparisonsession'),
        ),
    ]
