# Generated by Django 6.1.2 on 2026-10-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_add_comparisons'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonnarrative',
            name='individual_summaries',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
