from datetime import timedelta
import os

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "backend"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    "apps.common",
    "apps.users",
    'apps.imports',
    'apps.library',
    'apps.movies',
    'django_crontab',
    'django.contrib.postgres'
]

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL") or "gemini-embedding-001"
EMBEDDING_DIMENSIONS = int(os.getenv("EMBEDDING_DIMENSIONS") or 768)
EMBEDDING_MIN_REQUEST_INTERVAL_SECONDS = float(os.getenv("EMBEDDING_MIN_REQUEST_INTERVAL_SECONDS") or 1.5)
EMBEDDING_USE_SHARED_PACING = (os.getenv("EMBEDDING_USE_SHARED_PACING", "True") == "True")

TMDB_API_KEY = os.getenv("TMDB_API_KEY")
TMDB_MIN_REQUEST_INTERVAL_SECONDS = float(os.getenv("TMDB_MIN_REQUEST_INTERVAL_SECONDS") or 0.25)
TMDB_USE_SHARED_PACING = os.getenv("TMDB_USE_SHARED_PACING", "True") == "True"
TMDB_DISCOVER_MAX_PAGES = int(os.getenv("TMDB_DISCOVER_MAX_PAGES") or 5)
TMDB_DISCOVER_MIN_VOTE_COUNT = int(os.getenv("TMDB_DISCOVER_MIN_VOTE_COUNT") or 50)
TMDB_DISCOVER_NEW_RELEASE_WINDOW_DAYS = int(os.getenv("TMDB_DISCOVER_NEW_RELEASE_WINDOW_DAYS") or 90)
TMDB_DISCOVER_NEW_RELEASE_MIN_VOTE_COUNT = int(os.getenv("TMDB_DISCOVER_NEW_RELEASE_MIN_VOTE_COUNT") or 5)
TMDB_DISCOVER_START_YEAR = int(os.getenv("TMDB_DISCOVER_START_YEAR") or 1900)
TMDB_DISCOVER_PAGES_PER_BUCKET = int(os.getenv("TMDB_DISCOVER_PAGES_PER_BUCKET") or 1)
TMDB_DISCOVER_DECADE_MIN_VOTE_COUNT = int(os.getenv("TMDB_DISCOVER_DECADE_MIN_VOTE_COUNT") or 100)
TMDB_DISCOVER_GENRE_MIN_VOTE_COUNT = int(os.getenv("TMDB_DISCOVER_GENRE_MIN_VOTE_COUNT") or 50)

WIKIDATA_MIN_REQUEST_INTERVAL_SECONDS = float(os.getenv("WIKIDATA_MIN_REQUEST_INTERVAL_SECONDS") or 1.0)
WIKIDATA_USE_SHARED_PACING = os.getenv("WIKIDATA_USE_SHARED_PACING", "True") == "True"
WIKIDATA_USER_AGENT = os.getenv("WIKIDATA_USER_AGENT")

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.users.authentication.TrackingJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

CRONJOBS = [
    ("0 3 * * *", "django.core.management.call_command", ["seed_movie_catalog_daily"]),
    ("0 4 * * 0", "django.core.management.call_command", ["seed_movie_catalog_weekly"]),
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
