# Generated by Django 6.1.1 on 2026-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_create_user_entity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_guest', False), ('email__isnull', True), _connector='OR'), name='guest_users_have_no_email'),
        ),
    ]
