# Generated by Django 6.1.1 on 2026-09-16 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_add_embbedings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PAIRED', 'Paired')], max_length=16)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='WAITING', max_length=16)),
                ('users', models.ManyToManyField(related_name='swipe_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwipeSessionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('position', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_session_candidates', to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='swipe_sessions.swipesession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('SKIP', 'Skip'), ('WATCHLIST', 'Added to watchlist')], max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='swipe_sessions.swipesessioncandidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateJustification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='swipe_sessions.swipesessioncandidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='swipesessioncandidate',
            constraint=models.UniqueConstraint(fields=('session', 'movie'), name='unique_movie_per_swipe_session'),
        ),
        migrations.AddConstraint(
            model_name='swipesessioncandidate',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_position_per_swipe_session'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['user', 'action'], name='swipe_sessi_user_id_de8bfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='swipe',
            constraint=models.UniqueConstraint(fields=('user', 'candidate'), name='unique_swipe_per_user_candidate'),
        ),
    ]
