# Generated by Django 6.1.1 on 2026-09-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_sessions', '0001_add_swipe_session_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipesession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
