# Generated by Django 6.1.1 on 2026-09-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_sessions', '0002_add_last_seen_in_session_to_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatejustification',
            name='language',
        ),
    ]
