# Generated by Django 6.1.1 on 2026-09-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_sessions', '0003_remove_justification_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatejustification',
            name='generated_at',
        ),
    ]
