# Generated by Django 6.1.2 on 2026-10-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_add_session'),
        ('invites', '0001_add_invite_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='common.session'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='type',
            field=models.CharField(choices=[('comparison', 'Comparison'), ('paired_swipe', 'Paired Swipe')], max_length=16),
        ),
    ]
