# Generated by Django 6.1.1 on 2026-09-18 21:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('TERMS', 'Terms and Conditions'), ('PRIVACY', 'Privacy Policy')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['type', '-effective_at'],
                'constraints': [models.UniqueConstraint(fields=('type', 'version'), name='legal_document_unique_type_version'), models.UniqueConstraint(fields=('type', 'effective_at'), name='legal_document_unique_type_effective_at')],
            },
        ),
        migrations.CreateModel(
            name='UserLegalAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='legal_acceptance_unique_user_document')],
            },
        ),
    ]
