# Generated by Django 6.1.1 on 2026-09-10 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tmdb_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('poster_url', models.URLField(blank=True, default='')),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('streaming_providers', models.JSONField(blank=True, null=True)),
                ('metadata_fetched_at', models.DateTimeField(blank=True, help_text='When TMDb metadata was last (re)fetched for this row.', null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
