# Generated by Django 6.1.1 on 2026-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_create_movie_related_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='streaming_providers',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
        migrations.AddField(
            model_name='genre',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikidata_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metadata_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When Wikidata metadata was last (re)fetched for this row.', null=True),
        ),
    ]
