# Generated by Django 6.1.1 on 2026-09-14 14:08

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_migrate_entities_to_wikidata'),
    ]

    operations = [
        VectorExtension(),

        migrations.AddField(
            model_name='movie',
            name='embedding_source_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RemoveField(
            model_name="movie",
            name="embedding",
        ),

        migrations.AddField(
            model_name="movie",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='movie_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
