# Generated by Django 6.1.1 on 2026-09-20 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_embbedings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingBatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='submitted', max_length=16)),
                ('items', models.JSONField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='embedding_target_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='movie',
            name='embedding_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.embeddingbatchjob'),
        ),
    ]
